apiVersion: v1
kind: Service
metadata:
  name: megareports-service
spec:
  type: NodePort
  ports:
    - port: 80               # Puerto del servicio
      targetPort: 8080       # Puerto del contenedor
      nodePort: 30000
  selector:
    app: megareports
